language: ruby
rvm:
  - 2.7
install: gem install jekyll -v 3.9.0 && gem install s3_website && gem install bundler:1.14.6 && bundle install
script: bundle exec jekyll build
after_success: s3_website push
